name: Update Issues from Azure DevOps Board

on:
  repository_dispatch:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
      - uses: ./.github/actions/update-issues-action
        with:
          ADO_PAT: ${{ secrets.ADO_PAT }}
          ADO_ORG: ${{ secrets.ADO_ORG }}
          ADO_PROJ: ${{ secrets.ADO_PROJ }}
          ADO_TEAM: ${{ secrets.ADO_TEAM }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_USER: ${{ secrets.GH_USER }}
          GH_REPO: ${{ secrets.GH_REPO }}
          GH_ORG: ${{ secrets.GH_ORG }}
